Repository Hanaro-JSON/LifeOnHana_BE, pull requests merged in 2025-02, with the labels that each got.

#139 [fix] 🦥 테스트 코드 트랜잭션 처리
  src/test/java/com/example/lifeonhana/controller/AuthControllerTest.java
  src/test/java/com/example/lifeonhana/controller/LumpSumControllerTest.java
  src/test/java/com/example/lifeonhana/controller/ProductControllerTest.java
  src/test/java/com/example/lifeonhana/controller/UserControllerTest.java
  src/test/java/com/example/lifeonhana/controller/WalletControllerTest.java
  src/test/java/com/example/lifeonhana/controller/WhilickControllerTest.java
Labels: 🛠️ hotfix

#144 [fix] 🧚🏻‍♀️wallet balance 추가
  src/main/java/com/example/lifeonhana/entity/Wallet.java
  src/main/java/com/example/lifeonhana/repository/WalletRepository.java
  src/main/java/com/example/lifeonhana/service/LumpSumService.java
Labels: 🔨 fix

#145 [fix] 🧚🏻‍♀️wallet balance 수정
  src/main/java/com/example/lifeonhana/service/LumpSumService.java
  src/main/java/com/example/lifeonhana/service/WalletService.java
Labels: 🔨 fix

#146 [fix] 🦥 레디스 캐싱미스 처리
  src/main/java/com/example/lifeonhana/service/ProductInsightService.java
Labels: 🛠️ hotfix

#147 [fix] 🧚🏻‍♀️wallet balance 수정
  src/main/java/com/example/lifeonhana/service/WalletService.java
Labels: 🔨 fix

#155 [feat] 🧚🏻‍♀️ 입출금 내역 목돈 지급 추가
  src/main/java/com/example/lifeonhana/service/LumpSumService.java
  src/test/java/com/example/lifeonhana/controller/ProductControllerTest.java
Labels: ✨ feature, 🔨 fix
