Repository Hanaro-JSON/LifeOnHana_BE, pull requests merged in 2025-01, with the labels that each got.

#14 [fix] 🐢 entity 수정 #13
  .gitignore
  src/main/java/com/example/lifeonhana/entity/Account.java
  src/main/java/com/example/lifeonhana/entity/Article.java
  src/main/java/com/example/lifeonhana/entity/ArticleDictionary.java
  src/main/java/com/example/lifeonhana/entity/ArticleLike.java
  src/main/java/com/example/lifeonhana/entity/ArticleProduct.java
  src/main/java/com/example/lifeonhana/entity/History.java
  src/main/java/com/example/lifeonhana/entity/LumpSum.java
  src/main/java/com/example/lifeonhana/entity/Product.java
  src/main/java/com/example/lifeonhana/entity/ProductLike.java
  src/main/java/com/example/lifeonhana/entity/User.java
  src/main/java/com/example/lifeonhana/entity/Wallet.java
  src/main/resources/application.yml
Labels: 🔨 fix

#21 [feat] 🧚🏻‍♀️ Swagger 초기설정 추가
  build.gradle
  src/main/java/com/example/lifeonhana/ApiResponse.java
  src/main/java/com/example/lifeonhana/controller/AuthController.java
  src/main/java/com/example/lifeonhana/global/exception/BadRequestException.java
  src/main/java/com/example/lifeonhana/global/exception/BaseException.java
  src/main/java/com/example/lifeonhana/global/exception/ForbiddenException.java
  src/main/java/com/example/lifeonhana/global/exception/NotFoundException.java
  src/main/java/com/example/lifeonhana/global/exception/UnauthorizedException.java
  src/main/resources/application.yml
Labels: ✨ feature, 🔨 fix

#24 [fix] 🐢 로그인 오류 수정 #22
  src/main/java/com/example/lifeonhana/global/util/PasswordEncoderUtil.java
Labels: 🔨 fix

#27 [fix] jwtservice extractemail 이름 변경 #26
  src/main/java/com/example/lifeonhana/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/lifeonhana/service/AuthService.java
  src/main/java/com/example/lifeonhana/service/JwtService.java
Labels: 🔨 fix

#29 [test] 🐢 로그인 테스트 코드 작성 #28
  build.gradle
  src/main/java/com/example/lifeonhana/dto/AuthRequestDTO.java
  src/main/java/com/example/lifeonhana/dto/RefreshTokenRequestDTO.java
  src/main/java/com/example/lifeonhana/filter/JwtAuthenticationFilter.java
  src/test/java/com/example/lifeonhana/auth/AuthIntegrationTest.java
  src/test/java/com/example/lifeonhana/auth/AuthServiceTest.java
  src/test/java/com/example/lifeonhana/jwt/JwtAuthenticationFilterTest.java
  src/test/java/com/example/lifeonhana/jwt/JwtServiceTest.java
  src/test/java/com/example/lifeonhana/redis/RedisServiceTest.java
Labels: 🖍️ test

#31 [feat] 🧚🏻‍♀️ 하나지갑 정보 관련 api 구현
  .gitmessage.txt
  src/main/java/com/example/lifeonhana/controller/WalletController.java
  src/main/java/com/example/lifeonhana/dto/WalletDTO.java
  src/main/java/com/example/lifeonhana/entity/Wallet.java
  src/main/java/com/example/lifeonhana/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/lifeonhana/repository/UserRepository.java
  src/main/java/com/example/lifeonhana/repository/WalletRepository.java
  src/main/java/com/example/lifeonhana/service/WalletService.java
Labels: ✨ feature

#38 [feat] 🐢 history api 기능 구현 #33
  src/main/java/com/example/lifeonhana/config/SecurityConfig.java
  src/main/java/com/example/lifeonhana/controller/AuthController.java
  src/main/java/com/example/lifeonhana/controller/HistoryController.java
  src/main/java/com/example/lifeonhana/dto/request/AuthRequestDTO.java
  src/main/java/com/example/lifeonhana/dto/request/RefreshTokenRequestDTO.java
  src/main/java/com/example/lifeonhana/dto/response/AuthResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/CategoryStatResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/HistoryDetailResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/HistoryResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/MonthlyExpenseDetailResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/MonthlyExpenseResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/StatisticsResponseDTO.java
  src/main/java/com/example/lifeonhana/repository/HistoryRepository.java
  src/main/java/com/example/lifeonhana/repository/WalletRepository.java
  src/main/java/com/example/lifeonhana/service/AuthService.java
  src/main/java/com/example/lifeonhana/service/HistoryService.java
  src/main/resources/application.yml
  src/test/java/com/example/lifeonhana/auth/AuthIntegrationTest.java
  src/test/java/com/example/lifeonhana/auth/AuthServiceTest.java
  src/test/java/com/example/lifeonhana/history/HistoryIntegrationTest.java
Labels: ✨ feature

#52 [feat] 🦥 마이데이터 조회
  src/main/java/com/example/lifeonhana/controller/UserController.java
  src/main/java/com/example/lifeonhana/dto/response/MyDataResponseDTO.java
  src/main/java/com/example/lifeonhana/repository/HistoryRepository.java
  src/main/java/com/example/lifeonhana/service/UserService.java
Labels: ✨ feature

#53 [feat] 🦧 anthropic api 기반 대출 상품 추천 api
  src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
  src/main/java/com/example/lifeonhana/dto/request/LoanRecommendationRequest.java
  src/main/java/com/example/lifeonhana/dto/response/LoanProductResponse.java
  src/main/java/com/example/lifeonhana/repository/LoanProductRepository.java
  src/main/java/com/example/lifeonhana/service/ArticleService.java
  src/main/java/com/example/lifeonhana/service/FlaskService.java
  src/main/java/com/example/lifeonhana/service/LoanRecommendationService.java
Labels: ✨ feature

#54 [feat] 🧚🏻‍♀️ 좋아요한 상품 목록 조회 api
  src/main/java/com/example/lifeonhana/ApiResult.java
  src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
  src/main/java/com/example/lifeonhana/dto/response/ProductLikeResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/ProductResponseDTO.java
  src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
  src/main/java/com/example/lifeonhana/service/ProductLikeService.java
Labels: ✨ feature

#61 [feat] 🦥 사용자 취향 문구 조회
  src/main/java/com/example/lifeonhana/controller/UserController.java
  src/main/java/com/example/lifeonhana/dto/response/UserNicknameResponseDTO.java
  src/main/java/com/example/lifeonhana/entity/enums/ArticleCategory.java
  src/main/java/com/example/lifeonhana/repository/ArticleLikeRepository.java
  src/main/java/com/example/lifeonhana/service/UserService.java
Labels: ✨ feature

#62 [fix] 🔨 하나지갑 관련 api 수정
  src/main/java/com/example/lifeonhana/controller/WalletController.java
  src/main/java/com/example/lifeonhana/dto/WalletDTO.java
  src/main/java/com/example/lifeonhana/dto/request/WalletRequestDTO.java
  src/main/java/com/example/lifeonhana/dto/response/WalletResponseDTO.java
  src/main/java/com/example/lifeonhana/repository/UserRepository.java
  src/main/java/com/example/lifeonhana/repository/WalletRepository.java
  src/main/java/com/example/lifeonhana/service/WalletService.java
Labels: 🔨 fix

#64 [feat] 🦥 칼럼 목록 조회
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/main/java/com/example/lifeonhana/dto/response/ArticleListItemResponse.java
  src/main/java/com/example/lifeonhana/dto/response/ArticleListResponse.java
  src/main/java/com/example/lifeonhana/repository/ArticleLikeRepository.java
  src/main/java/com/example/lifeonhana/repository/ArticleRepository.java
  src/main/java/com/example/lifeonhana/service/ArticleService.java
Labels: ✨ feature

#66 [feat] 🦥 칼럼 검색 기능
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/main/java/com/example/lifeonhana/dto/response/ArticleListResponse.java
  src/main/java/com/example/lifeonhana/dto/response/ArticleSearchResponseDto.java
  src/main/java/com/example/lifeonhana/repository/ArticleLikeRepository.java
  src/main/java/com/example/lifeonhana/repository/ArticleRepository.java
  src/main/java/com/example/lifeonhana/service/ArticleService.java
Labels: ✨ feature

#67 [feat] 🦧 anthropic 기반 상품 기대효과 생성 api
  src/main/java/com/example/lifeonhana/controller/AccountController.java
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/main/java/com/example/lifeonhana/controller/ArticleLikeController.java
  src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
  src/main/java/com/example/lifeonhana/controller/ProductInsightController.java
  src/main/java/com/example/lifeonhana/dto/request/ProductInsightRequest.java
  src/main/java/com/example/lifeonhana/dto/response/ProductInsightResponse.java
  src/main/java/com/example/lifeonhana/repository/HistoryRepository.java
  src/main/java/com/example/lifeonhana/repository/ProductRepository.java
  src/main/java/com/example/lifeonhana/service/ProductInsightService.java
Labels: ✨ feature

#68 [feat] 🧚🏻‍♀️ 상품 조회 관련 api 구현
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/main/java/com/example/lifeonhana/controller/ProductController.java
  src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
  src/main/java/com/example/lifeonhana/dto/response/LifeProductResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/LoanProductDetailResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/ProductListResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/SavingProductResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/SimpleProductResponseDTO.java
  src/main/java/com/example/lifeonhana/repository/LoanProductRepository.java
  src/main/java/com/example/lifeonhana/repository/ProductRepository.java
  src/main/java/com/example/lifeonhana/service/ProductLikeService.java
  src/main/java/com/example/lifeonhana/service/ProductService.java
Labels: ✨ feature

#72 [feat] 🦧 계좌 이체 api 구현
  src/main/java/com/example/lifeonhana/controller/AccountController.java
  src/main/java/com/example/lifeonhana/dto/request/AccountTransferRequest.java
  src/main/java/com/example/lifeonhana/dto/response/AccountTransferResponse.java
  src/main/java/com/example/lifeonhana/entity/Account.java
  src/main/java/com/example/lifeonhana/global/exception/InsufficientBalanceException.java
  src/main/java/com/example/lifeonhana/repository/AccountRepository.java
  src/main/java/com/example/lifeonhana/service/AccountService.java
Labels: ✨ feature

#73 [feat] 🧚🏻‍♀️ 무한스크롤 구현
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
  src/main/java/com/example/lifeonhana/dto/response/ArticleSearchResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/ProductListResponseDTO.java
  src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
  src/main/java/com/example/lifeonhana/repository/ProductRepository.java
  src/main/java/com/example/lifeonhana/service/ArticleService.java
  src/main/java/com/example/lifeonhana/service/ProductLikeService.java
  src/main/java/com/example/lifeonhana/service/ProductService.java
Labels: 💡 refactor

#75 [feat] 🦧 상품 좋아요 생성, 취소 api && 기대효과 응답에 좋아요 여부 추가
  src/main/java/com/example/lifeonhana/controller/ProductLikeController.java
  src/main/java/com/example/lifeonhana/dto/response/ProductInsightResponse.java
  src/main/java/com/example/lifeonhana/entity/ProductLike.java
  src/main/java/com/example/lifeonhana/entity/ProductLikeId.java
  src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
  src/main/java/com/example/lifeonhana/service/ProductInsightService.java
  src/main/java/com/example/lifeonhana/service/ProductLikeService.java
Labels: ✨ feature

#76 [feat] 🧚🏻‍♀️목돈 신청 api #69
  src/main/java/com/example/lifeonhana/controller/LumpSumController.java
  src/main/java/com/example/lifeonhana/dto/request/LumpSumRequestDTO.java
  src/main/java/com/example/lifeonhana/dto/response/LumpSumResponseDTO.java
  src/main/java/com/example/lifeonhana/entity/LumpSum.java
  src/main/java/com/example/lifeonhana/repository/AccountRepository.java
  src/main/java/com/example/lifeonhana/repository/LumpSumRepository.java
  src/main/java/com/example/lifeonhana/repository/WalletRepository.java
  src/main/java/com/example/lifeonhana/service/LumpSumService.java
  src/main/java/com/example/lifeonhana/service/WalletService.java
Labels: ✨ feature

#78 [fix] 🦧 계좌 목록 반환 값에 id 추가
  src/main/java/com/example/lifeonhana/dto/response/AccountResponseDTO.java
  src/main/java/com/example/lifeonhana/service/AccountService.java
Labels: 🔨 fix

#79 [refactor] 🧚🏻‍♀️ 상품 상세 좋아요 여부 추가 #77
  src/main/java/com/example/lifeonhana/dto/response/LifeProductResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/LoanProductDetailResponseDTO.java
  src/main/java/com/example/lifeonhana/dto/response/SavingProductResponseDTO.java
  src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
  src/main/java/com/example/lifeonhana/service/ProductService.java
Labels: ✨ feature

#82 [fix] 최초로그인 관리 수정 #81
  src/main/java/com/example/lifeonhana/dto/response/AuthResponseDTO.java
  src/main/java/com/example/lifeonhana/service/AuthService.java
  src/main/resources/application.yml
  src/test/java/com/example/lifeonhana/auth/AuthIntegrationTest.java
  src/test/java/com/example/lifeonhana/auth/AuthServiceTest.java
  src/test/java/com/example/lifeonhana/history/HistoryIntegrationTest.java
Labels: 🔨 fix

#83 [hotfix] 🦥 레디스 캐싱미스 처리
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/main/java/com/example/lifeonhana/repository/ArticleRepository.java
  src/main/java/com/example/lifeonhana/service/ArticleLikeService.java
  src/main/java/com/example/lifeonhana/service/ArticleService.java
Labels: 🛠️ hotfix

#85 [fix] 🦧 Flask url 도메인으로 변경
  src/main/java/com/example/lifeonhana/service/ArticleService.java
  src/main/java/com/example/lifeonhana/service/FlaskService.java
  src/main/java/com/example/lifeonhana/service/LoanRecommendationService.java
  src/main/java/com/example/lifeonhana/service/ProductInsightService.java
Labels: 🔨 fix

#89 [fix] 🦥 레디스 캐싱미스 처리&&사용자 취향 수정
  src/main/java/com/example/lifeonhana/batch/RedisToDatabaseSynchronizer.java
  src/main/java/com/example/lifeonhana/repository/ArticleRepository.java
  src/main/java/com/example/lifeonhana/repository/ProductLikeRepository.java
  src/main/java/com/example/lifeonhana/repository/ProductRepository.java
  src/main/java/com/example/lifeonhana/service/ArticleLikeService.java
  src/main/java/com/example/lifeonhana/service/ProductLikeService.java
  src/main/java/com/example/lifeonhana/service/UserService.java
Labels: 🔨 fix

#94 [fix] 🧚🏻‍♀️하나지갑 응답보내주는 형식 수정 #93
  src/main/java/com/example/lifeonhana/service/WalletService.java
Labels: 🔨 fix

#99 [fix] 🧚🏻‍♀️ 목돈신청 변경
  src/main/java/com/example/lifeonhana/controller/LumpSumController.java
  src/main/java/com/example/lifeonhana/dto/request/LumpSumRequestDTO.java
  src/main/java/com/example/lifeonhana/dto/request/WalletRequestDTO.java
  src/main/java/com/example/lifeonhana/dto/response/LumpSumResponseDTO.java
  src/main/java/com/example/lifeonhana/global/exception/BadRequestException.java
  src/main/java/com/example/lifeonhana/global/exception/BaseException.java
  src/main/java/com/example/lifeonhana/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/lifeonhana/repository/WalletRepository.java
  src/main/java/com/example/lifeonhana/service/LumpSumService.java
Labels: 🔨 fix

#102 [test] accountController 테스트 코드 작성
  src/main/java/com/example/lifeonhana/controller/AccountController.java
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/main/java/com/example/lifeonhana/dto/response/ErrorResponse.java
  src/main/java/com/example/lifeonhana/global/exception/ErrorCode.java
  src/main/java/com/example/lifeonhana/global/exception/GlobalExceptionHandler.java
  src/main/java/com/example/lifeonhana/service/AccountService.java
  src/test/java/com/example/lifeonhana/controller/AccountControllerTest.java
  src/test/resources/application-test.yml
  src/test/resources/test-data.sql
Labels: 🖍️ test

#104 [test] 🦥 article 테스트 코드 작성
  src/main/java/com/example/lifeonhana/controller/ArticleController.java
  src/test/java/com/example/lifeonhana/controller/ArticleControllerTest.java
Labels: 🖍️ test

#106 [test] 🦥 articleLike 테스트 코드 작성
  src/test/java/com/example/lifeonhana/controller/ArticleLikeControllerTest.java
Labels: 🖍️ test

#108 [test] 🦧 productInsight 테스트코드 작성
  src/main/java/com/example/lifeonhana/controller/ProductInsightController.java
  src/main/java/com/example/lifeonhana/service/ProductInsightService.java
  src/test/java/com/example/lifeonhana/productInsight/ProductInsightControllerTest.java
  src/test/resources/application-test.yml
Labels: 🖍️ test

#110 [test] 🦧 LoanRecommendationController 테스트 코드 작성
  src/main/java/com/example/lifeonhana/controller/LoanRecommendationController.java
  src/main/java/com/example/lifeonhana/service/LoanRecommendationService.java
  src/test/java/com/example/lifeonhana/controller/LoanRecommendationControllerTest.java
  src/test/java/com/example/lifeonhana/controller/ProductInsightControllerTest.java
Labels: 🖍️ test

#116 [fix] 🦥 기사 테스트코드 수정
  src/test/java/com/example/lifeonhana/controller/ArticleControllerTest.java
  src/test/java/com/example/lifeonhana/controller/ArticleLikeControllerTest.java
Labels: 🛠️ hotfix

#118 [fix] 🧚🏻‍♀️cors 설정 추가 및 samesite 설정 #117
  src/main/java/com/example/lifeonhana/config/SecurityConfig.java
Labels: 🔨 fix

#122 [hotfix] 🧚🏻‍♀️백엔드 경로 /api 추가 #117
  src/main/java/com/example/lifeonhana/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🛠️ hotfix

#123 [test] 🧚🏻‍♀️lumpsum controller test code #119
  src/test/java/com/example/lifeonhana/controller/LumpSumControllerTest.java
Labels: 🖍️ test

#127 [test] 🧚🏻‍♀️ product controller
  src/test/java/com/example/lifeonhana/controller/LumpSumControllerTest.java
  src/test/java/com/example/lifeonhana/controller/ProductControllerTest.java
Labels: 🖍️ test

#128 [test] 🧚🏻‍♀️Wallet controller test code #121
  src/main/java/com/example/lifeonhana/config/SecurityConfig.java
  src/main/resources/application.yml
  src/test/java/com/example/lifeonhana/controller/WalletControllerTest.java
Labels: 🖍️ test

#130 [feat] 🦥 actuator설정&&이자 지급 기능 추가
  build.gradle
  src/main/java/com/example/lifeonhana/repository/AccountRepository.java
  src/main/java/com/example/lifeonhana/service/AccountService.java
  src/main/resources/application.yml
Labels: ✨ feature
